### ISSUE TITLE
Can't find EPi.Carousel.Bootstrap on NuGet

### ISSUE THREAD

**Issue by charlottewideen** [Geta/EPi.Carousel#2]
I am trying to find EPi.Carousel.Bootstrap on NuGet, but I can't find it.

**Comment by frederikvig** [comment]
http://nuget.episerver.com/en/OtherPages/Package/?packageId=EPi.Carousel.Bootstrap

**Comment by charlottewideen** [comment]
Thanks! I missed that it was in episervers nuget
